### ISSUE TITLE
Why did you spam Sindre?

### ISSUE THREAD

**Issue by ajwhite** [EmpireWorld/ama#1]
We're all dying to know more about https://github.com/sindresorhus/ama/issues/485

**Comment by EmpireWorld** [comment]
I didn't spammed him in the way you think, i just contacted him about inviting him to an organization and project but he didn't answered me in a **long period**, so i added him **without his permission**, so he thinks i spammed him, but i d my target is just an **invitation**.

I thought he enjoyed to be a part of my community, because the project is about Node.js and i thought he might enjoy.

Anyway, now we are friends. :smile:

If you have any more questions, You are welcome. just ask.

If you need more info, let me know.

Have a nice day!

**Comment by ajwhite** [comment]
Ah, yes, the whole motivation behind [limiting repository invites](https://github.com/blog/2170-repository-invitations)
